Add card and cardDTO classes
isaacphysics/isaac-api pull request #281
Opened 2020-08-21 10:14 UTC by Scratchcat1

---

**Pull Request Check List**
- [ ] Unit Tests & Regression Tests Added (Optional)
- [ ] Removed Unnecessary Logs/System.Outs/Comments/TODOs
- [ ] Added enough Logging to monitor expected behaviour change
- [ ] Security - Injection - everything run by an interpreter (SQL, OS...) is either validated or escaped
- [ ] Security - Data Exposure - PII is not stored or sent unencrypted
- [ ] Security - Access Control - Check authorisation on every new endpoint
- [ ] Security - New dependency - configured sensibly not relying on defaults
- [ ] Security - New dependency - Searched for any know vulnerabilities
- [ ] Security - New dependency - Signed up team to mailing list
- [ ] Security - New dependency - Added to dependency list
- [ ] DB schema changes - postgres-rutherford-create-script updated
- [ ] DB schema changes - upgrade script created matching create script
- [ ] Updated Release Procedure & Documentation (& Considered Implications to Previous Versions)
- [ ] Peer-Reviewed

2020-08-24 14:55 UTC, Morpheu5 approved these changes

2020-09-03 15:55 UTC, mlt47 requested changes
This looks good so far. The goal of the task is to enable the content team to create card like items in the json defined content through using the content editor.
We need another content object to represent a card deck to hold these content created cards.

2020-09-03 15:55 UTC, mlt47 commented on src/main/java/uk/ac/cam/cl/dtg/isaac/dos/IsaacCard.java
> +@JsonContentType("card")
In the front-end branch, src/app/components/content/IsaacContent.tsx  is currently  looking for json objects with the property "type" with value "isaacCard". They need to be consistent for the front end to know which component to render. I think I prefer `card` as there is nothing particularly Isaac specific about it.

2020-09-15 13:15 UTC, mlt47 approved these changes
Good. Made a little comment, but it does not require changes.

2020-09-17 13:34 UTC, merged