Prevent ETL from indexing invalid quizzes.
isaacphysics/isaac-api pull request #352
Opened 2021-06-08 11:58 UTC by Morpheu5

If a quiz's top-level children array contains anything that is not an isaacQuizSection, things can unexpectedly break downstream in surprising and confusing ways. This PR mitigates surprise and confusion.

---

**Pull Request Check List**
- [x] Removed Unnecessary Logs/System.Outs/Comments/TODOs
- [x] Added enough Logging to monitor expected behaviour change
- [ ] Peer-Reviewed

2021-06-08 13:48 UTC, jsharkey13 requested changes
You definitely need a sensible and clearly worded `this.registerContentProblem(...)` too, otherwise this will only add further confusion!

2021-06-08 14:29 UTC, Morpheu5 commented
> You definitely need a sensible and clearly worded `this.registerContentProblem(...)` too, otherwise this will only add further confusion!

Indeed, done!

2021-06-09 08:24 UTC, jsharkey13 approved these changes
I'd like to leave this for the next release, so will merge tomorrow.

2021-06-09 14:48 UTC, merged

2021-06-09 14:48 UTC, jsharkey13 commented
(Release went smoothly today, so merging now)