Schedule assignment
isaacphysics/isaac-api pull request #468
Opened 2022-07-22 14:54 UTC by chrisjpurdy

This adds the ability to add a scheduled start date to an assignment, which gets saved in the DB and will be used to schedule an email to groups who are assigned it once the time comes around (this will be another PR, for now the assignment is saved but no email is sent).

---

Only remaining things to do is add a limit to how far in the future assignments can be scheduled for, then this should be ready for review.

2022-07-28 13:59 UTC, mwtrew requested changes

2022-07-29 15:22 UTC, chrisjpurdy commented on src/main/java/uk/ac/cam/cl/dtg/isaac/dao/PgAssignmentPersistenceManager.java
> +                pst.setNull(2, Types.TIMESTAMP);
Good point, have implemented that 👍

2022-07-29 15:28 UTC, chrisjpurdy commented on src/main/java/uk/ac/cam/cl/dtg/isaac/api/AssignmentFacade.java
> +                    .stream().filter(a -> null == a.getScheduledStartDate() || !a.getScheduledStartDate().before(new Date()))
Great spot, thanks - I should have got a pen and paper out for that one 😅 

I love how your suggestion looks like the Rust compilers error messages btw: 
![image](https://user-images.githubusercontent.com/33040507/181792854-c59347e0-2dc5-43f5-b8fa-a6f6401fc4aa.png)

2022-08-02 10:29 UTC, mwtrew approved these changes

2022-08-02 11:25 UTC, merged