Rewrite cloze question validator
isaacphysics/isaac-api pull request #487
Opened 2022-09-27 15:52 UTC by jsharkey13

Previously the validator didn't correctly support subset matching (in fact it was badly broken, using sets which did not preserve the order of the items submitted!), and did not allow question setters to subset match with blanks.
Now an answer can be specified as (id1, NULL_ID, NULL_ID) and marked as allowing subset matches, and then submissions such as (id1, id2, id3) or (id1, id3, NULL) could match it. This should be useful for adding common wrong answer feedback.

There is an open question about whether subset matching should allow empty submissions from users to match (provided the entire answer is not empty), but at present this is not allowed.

2022-09-29 14:50 UTC, mwtrew requested changes

2022-09-29 15:13 UTC, jsharkey13 commented on src/main/java/uk/ac/cam/cl/dtg/isaac/quiz/IsaacClozeValidator.java
> +                    feedback = new Content("You did not provide a valid answer; it does not contain an item for each gap.");
Great spot, I proposed a fix to you and I will implement and push it now!

2022-09-29 15:15 UTC, jsharkey13 commented on src/test/java/uk/ac/cam/cl/dtg/isaac/quiz/IsaacClozeValidatorTest.java
> +public class IsaacClozeValidatorTest {
I'm after that >90% code coverage for all internal validators, and since that's this entire PR, I've managed to get the patch coverage to 94% too! 🎉

2022-10-06 14:24 UTC, mwtrew approved these changes

2022-10-07 11:37 UTC, merged