Allow page-level types to be deprecated and superseded
isaacphysics/isaac-api pull request #598
Opened 2024-04-25 15:30 UTC by jsharkey13

This is a change from _any_ content being able to be deprecated, to just top-level page types (i.e. those that extend SeguePage). We did not do anything with deprecated set on any other content, so this change is safe to make and reflects the actual behaviour.
This also moves supersededBy to the SeguePage and subclasses, so that more than just question pages can be superseded.
It also tidies up other classes that had one or both of these properties but where we were not using them. A similar change to the frontend types exists to demonstrate that we only used these for SeguePage level objects.

I have tested that this has not broken any existing content, and also verified that ContentSummaryDTOs still get the two properties mapped across as expected.

2024-04-25 15:40 UTC, jsharkey13 commented
This is probably where the properties should have been added in the first place. I am still a little worried about odd cases like wildcards or past question attempts where `deprecated` might have gotten into the database and now be unable to be un-mapped. I believe wildcards are the only problematic case where we used an unconfigured ObjectMapper which included null values, however!

2024-04-25 16:15 UTC, jsharkey13 commented
This goes with https://github.com/isaacphysics/isaac-react-app/pull/963, although neither depends on the other! They both confirm that the move is safe to make, however.

2024-04-29 08:57 UTC, skyepurchase requested changes
LGTM. But, please fix the CodeQL warnings

2024-04-29 10:50 UTC, skyepurchase approved these changes

2024-04-29 10:50 UTC, merged